# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Btp.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        MainWindow.setMaximumSize(QtCore.QSize(800, 600))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:/Users/Asus/PycharmProjects/practice1/img/agent.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setDocumentMode(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(30, 20, 491, 301))
        self.widget.setAutoFillBackground(False)
        self.widget.setObjectName("widget")
        self.label_T = QtWidgets.QLabel(self.widget)
        self.label_T.setGeometry(QtCore.QRect(160, 160, 50, 50))
        self.label_T.setBaseSize(QtCore.QSize(50, 50))
        self.label_T.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);\n"
"border-width: 1px;\n"
"border-style: solid;")
        self.label_T.setText("")
        self.label_T.setPixmap(QtGui.QPixmap("C:/Users/Asus/PycharmProjects/practice1/img/agent.png"))
        self.label_T.setScaledContents(False)
        self.label_T.setOpenExternalLinks(False)
        self.label_T.setObjectName("label_T")
        self.label_17 = QtWidgets.QLabel(self.widget)
        self.label_17.setGeometry(QtCore.QRect(110, 160, 50, 50))
        self.label_17.setBaseSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(12)
        self.label_17.setFont(font)
        self.label_17.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);\n"
"border-width: 1px;\n"
"border-style: solid;")
        self.label_17.setText("")
        self.label_17.setScaledContents(False)
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setOpenExternalLinks(False)
        self.label_17.setObjectName("label_17")
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setGeometry(QtCore.QRect(60, 60, 50, 50))
        self.label_6.setBaseSize(QtCore.QSize(50, 50))
        self.label_6.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);\n"
"border-width: 1px;\n"
"border-style: solid;")
        self.label_6.setText("")
        self.label_6.setScaledContents(False)
        self.label_6.setOpenExternalLinks(False)
        self.label_6.setObjectName("label_6")
        self.label_C = QtWidgets.QLabel(self.widget)
        self.label_C.setGeometry(QtCore.QRect(110, 160, 50, 50))
        self.label_C.setBaseSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_C.setFont(font)
        self.label_C.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"background-color: rgb(85, 170, 255);\n"
"border-color: rgb(0, 0, 0);\n"
"border-width: 1px;\n"
"border-style: solid;")
        self.label_C.setScaledContents(False)
        self.label_C.setAlignment(QtCore.Qt.AlignCenter)
        self.label_C.setOpenExternalLinks(False)
        self.label_C.setObjectName("label_C")
        self.label_10 = QtWidgets.QLabel(self.widget)
        self.label_10.setGeometry(QtCore.QRect(60, 110, 50, 50))
        self.label_10.setBaseSize(QtCore.QSize(50, 50))
        self.label_10.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);\n"
"border-width: 1px;\n"
"border-style: solid;")
        self.label_10.setText("")
        self.label_10.setScaledContents(False)
        self.label_10.setOpenExternalLinks(False)
        self.label_10.setObjectName("label_10")
        self.label_9 = QtWidgets.QLabel(self.widget)
        self.label_9.setGeometry(QtCore.QRect(10, 110, 50, 50))
        self.label_9.setBaseSize(QtCore.QSize(50, 50))
        self.label_9.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);\n"
"border-width: 1px;\n"
"border-style: solid;")
        self.label_9.setText("")
        self.label_9.setScaledContents(False)
        self.label_9.setOpenExternalLinks(False)
        self.label_9.setObjectName("label_9")
        self.label_15 = QtWidgets.QLabel(self.widget)
        self.label_15.setGeometry(QtCore.QRect(10, 160, 50, 50))
        self.label_15.setBaseSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_15.setFont(font)
        self.label_15.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_15.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);\n"
"border-width: 1px;\n"
"border-style: solid;")
        self.label_15.setText("")
        self.label_15.setScaledContents(False)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setIndent(-1)
        self.label_15.setOpenExternalLinks(False)
        self.label_15.setObjectName("label_15")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setGeometry(QtCore.QRect(160, 10, 50, 50))
        self.label_4.setBaseSize(QtCore.QSize(50, 50))
        self.label_4.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);\n"
"border-width: 1px;\n"
"border-style: solid;")
        self.label_4.setText("")
        self.label_4.setScaledContents(False)
        self.label_4.setOpenExternalLinks(False)
        self.label_4.setObjectName("label_4")
        self.label_B = QtWidgets.QLabel(self.widget)
        self.label_B.setGeometry(QtCore.QRect(60, 160, 50, 50))
        self.label_B.setBaseSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_B.setFont(font)
        self.label_B.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"background-color: rgb(85, 170, 255);\n"
"border-color: rgb(0, 0, 0);\n"
"border-width: 1px;\n"
"border-style: solid;")
        self.label_B.setScaledContents(False)
        self.label_B.setAlignment(QtCore.Qt.AlignCenter)
        self.label_B.setOpenExternalLinks(False)
        self.label_B.setObjectName("label_B")
        self.label_18 = QtWidgets.QLabel(self.widget)
        self.label_18.setGeometry(QtCore.QRect(160, 160, 50, 50))
        self.label_18.setBaseSize(QtCore.QSize(50, 50))
        self.label_18.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);\n"
"border-width: 1px;\n"
"border-style: solid;")
        self.label_18.setText("")
        self.label_18.setScaledContents(False)
        self.label_18.setOpenExternalLinks(False)
        self.label_18.setObjectName("label_18")
        self.label_11 = QtWidgets.QLabel(self.widget)
        self.label_11.setGeometry(QtCore.QRect(110, 110, 50, 50))
        self.label_11.setBaseSize(QtCore.QSize(50, 50))
        self.label_11.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);\n"
"border-width: 1px;\n"
"border-style: solid;")
        self.label_11.setText("")
        self.label_11.setScaledContents(False)
        self.label_11.setOpenExternalLinks(False)
        self.label_11.setObjectName("label_11")
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setGeometry(QtCore.QRect(10, 60, 50, 50))
        self.label_5.setBaseSize(QtCore.QSize(50, 50))
        self.label_5.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);\n"
"border-width: 1px;\n"
"border-style: solid;")
        self.label_5.setText("")
        self.label_5.setScaledContents(False)
        self.label_5.setOpenExternalLinks(False)
        self.label_5.setObjectName("label_5")
        self.label_8 = QtWidgets.QLabel(self.widget)
        self.label_8.setGeometry(QtCore.QRect(160, 60, 50, 50))
        self.label_8.setBaseSize(QtCore.QSize(50, 50))
        self.label_8.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);\n"
"border-width: 1px;\n"
"border-style: solid;")
        self.label_8.setText("")
        self.label_8.setScaledContents(False)
        self.label_8.setOpenExternalLinks(False)
        self.label_8.setObjectName("label_8")
        self.label_7 = QtWidgets.QLabel(self.widget)
        self.label_7.setGeometry(QtCore.QRect(110, 60, 50, 50))
        self.label_7.setBaseSize(QtCore.QSize(50, 50))
        self.label_7.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);\n"
"border-width: 1px;\n"
"border-style: solid;")
        self.label_7.setText("")
        self.label_7.setScaledContents(False)
        self.label_7.setOpenExternalLinks(False)
        self.label_7.setObjectName("label_7")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(60, 10, 50, 50))
        self.label_2.setBaseSize(QtCore.QSize(50, 50))
        self.label_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);\n"
"border-width: 1px;\n"
"border-style: solid;")
        self.label_2.setText("")
        self.label_2.setScaledContents(False)
        self.label_2.setOpenExternalLinks(False)
        self.label_2.setObjectName("label_2")
        self.label_16 = QtWidgets.QLabel(self.widget)
        self.label_16.setGeometry(QtCore.QRect(60, 160, 50, 50))
        self.label_16.setBaseSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(12)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);\n"
"border-width: 1px;\n"
"border-style: solid;")
        self.label_16.setText("")
        self.label_16.setScaledContents(False)
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setOpenExternalLinks(False)
        self.label_16.setObjectName("label_16")
        self.label_12 = QtWidgets.QLabel(self.widget)
        self.label_12.setGeometry(QtCore.QRect(160, 110, 50, 50))
        self.label_12.setBaseSize(QtCore.QSize(50, 50))
        self.label_12.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);\n"
"border-width: 1px;\n"
"border-style: solid;")
        self.label_12.setText("")
        self.label_12.setScaledContents(False)
        self.label_12.setOpenExternalLinks(False)
        self.label_12.setObjectName("label_12")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(10, 10, 50, 50))
        self.label.setBaseSize(QtCore.QSize(50, 50))
        self.label.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);\n"
"border-width: 1px;\n"
"border-style: solid;")
        self.label.setText("")
        self.label.setScaledContents(False)
        self.label.setOpenExternalLinks(False)
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setGeometry(QtCore.QRect(110, 10, 50, 50))
        self.label_3.setBaseSize(QtCore.QSize(50, 50))
        self.label_3.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);\n"
"border-width: 1px;\n"
"border-style: solid;")
        self.label_3.setText("")
        self.label_3.setScaledContents(False)
        self.label_3.setOpenExternalLinks(False)
        self.label_3.setObjectName("label_3")
        self.label_A = QtWidgets.QLabel(self.widget)
        self.label_A.setGeometry(QtCore.QRect(10, 160, 50, 50))
        self.label_A.setBaseSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_A.setFont(font)
        self.label_A.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"background-color: rgb(85, 170, 255);\n"
"border-color: rgb(0, 0, 0);\n"
"border-width: 1px;\n"
"border-style: solid;")
        self.label_A.setScaledContents(False)
        self.label_A.setAlignment(QtCore.Qt.AlignCenter)
        self.label_A.setIndent(-1)
        self.label_A.setOpenExternalLinks(False)
        self.label_A.setObjectName("label_A")
        self.label_BG = QtWidgets.QLabel(self.widget)
        self.label_BG.setGeometry(QtCore.QRect(0, 0, 220, 220))
        self.label_BG.setText("")
        self.label_BG.setPixmap(QtGui.QPixmap("C:/Users/Asus/PycharmProjects/practice1/img/bg.png"))
        self.label_BG.setAlignment(QtCore.Qt.AlignCenter)
        self.label_BG.setObjectName("label_BG")
        self.label_O = QtWidgets.QLabel(self.widget)
        self.label_O.setGeometry(QtCore.QRect(240, 160, 51, 51))
        self.label_O.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);\n"
"border-width: 1px;\n"
"border-style: solid;")
        self.label_O.setText("")
        self.label_O.setPixmap(QtGui.QPixmap("C:/Users/Asus/PycharmProjects/practice1/img/obstacle.jpg"))
        self.label_O.setAlignment(QtCore.Qt.AlignCenter)
        self.label_O.setObjectName("label_O")
        self.layoutWidget = QtWidgets.QWidget(self.widget)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 250, 221, 31))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.Astarbtn = QtWidgets.QPushButton(self.layoutWidget)
        self.Astarbtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Astarbtn.setObjectName("Astarbtn")
        self.horizontalLayout_3.addWidget(self.Astarbtn)
        self.dfsbtn = QtWidgets.QPushButton(self.layoutWidget)
        self.dfsbtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.dfsbtn.setObjectName("dfsbtn")
        self.horizontalLayout_3.addWidget(self.dfsbtn)
        self.bfsbtn = QtWidgets.QPushButton(self.layoutWidget)
        self.bfsbtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bfsbtn.setObjectName("bfsbtn")
        self.horizontalLayout_3.addWidget(self.bfsbtn)
        self.layoutWidget1 = QtWidgets.QWidget(self.widget)
        self.layoutWidget1.setGeometry(QtCore.QRect(310, 230, 150, 54))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_19 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_19.setObjectName("label_19")
        self.verticalLayout.addWidget(self.label_19)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.depthlimit_input = QtWidgets.QLineEdit(self.layoutWidget1)
        self.depthlimit_input.setMaxLength(2)
        self.depthlimit_input.setObjectName("depthlimit_input")
        self.horizontalLayout_4.addWidget(self.depthlimit_input)
        self.idsbtn = QtWidgets.QPushButton(self.layoutWidget1)
        self.idsbtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.idsbtn.setObjectName("idsbtn")
        self.horizontalLayout_4.addWidget(self.idsbtn)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.layoutWidget.raise_()
        self.label_BG.raise_()
        self.label_9.raise_()
        self.label_10.raise_()
        self.label_12.raise_()
        self.label_7.raise_()
        self.label_11.raise_()
        self.label_5.raise_()
        self.label_6.raise_()
        self.label_8.raise_()
        self.label_4.raise_()
        self.label_3.raise_()
        self.label_2.raise_()
        self.label.raise_()
        self.label_16.raise_()
        self.label_17.raise_()
        self.label_15.raise_()
        self.label_18.raise_()
        self.label_B.raise_()
        self.label_T.raise_()
        self.label_C.raise_()
        self.label_A.raise_()
        self.label_O.raise_()
        self.layoutWidget.raise_()
        self.widget_4 = QtWidgets.QWidget(self.centralwidget)
        self.widget_4.setGeometry(QtCore.QRect(30, 320, 751, 221))
        self.widget_4.setObjectName("widget_4")
        self.label_action = QtWidgets.QLabel(self.widget_4)
        self.label_action.setGeometry(QtCore.QRect(390, 0, 151, 23))
        self.label_action.setObjectName("label_action")
        self.textEdit = QtWidgets.QTextEdit(self.widget_4)
        self.textEdit.setGeometry(QtCore.QRect(390, 30, 331, 191))
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName("textEdit")
        self.layoutWidget2 = QtWidgets.QWidget(self.widget_4)
        self.layoutWidget2.setGeometry(QtCore.QRect(0, 0, 264, 25))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_13 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout.addWidget(self.label_13)
        self.lcdTimeComplexity = QtWidgets.QLCDNumber(self.layoutWidget2)
        self.lcdTimeComplexity.setStyleSheet("color: rgb(0, 0, 0);\n"
"border: none;\n"
"")
        self.lcdTimeComplexity.setDigitCount(12)
        self.lcdTimeComplexity.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdTimeComplexity.setObjectName("lcdTimeComplexity")
        self.horizontalLayout.addWidget(self.lcdTimeComplexity)
        self.layoutWidget3 = QtWidgets.QWidget(self.widget_4)
        self.layoutWidget3.setGeometry(QtCore.QRect(0, 60, 184, 25))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget3)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_14 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_2.addWidget(self.label_14)
        self.lcdDepth = QtWidgets.QLCDNumber(self.layoutWidget3)
        self.lcdDepth.setStyleSheet("color: rgb(0, 0, 0);\n"
"border: none;\n"
"")
        self.lcdDepth.setDigitCount(12)
        self.lcdDepth.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdDepth.setObjectName("lcdDepth")
        self.horizontalLayout_2.addWidget(self.lcdDepth)
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        self.widget_2.setGeometry(QtCore.QRect(550, 20, 231, 291))
        self.widget_2.setObjectName("widget_2")
        self.lineEdit = QtWidgets.QLineEdit(self.widget_2)
        self.lineEdit.setGeometry(QtCore.QRect(0, 0, 50, 50))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit.setFont(font)
        self.lineEdit.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit.setMaxLength(1)
        self.lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.widget_2)
        self.lineEdit_2.setGeometry(QtCore.QRect(50, 0, 50, 50))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_2.setMaxLength(1)
        self.lineEdit_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.widget_2)
        self.lineEdit_3.setGeometry(QtCore.QRect(100, 0, 50, 50))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_3.setMaxLength(1)
        self.lineEdit_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.widget_2)
        self.lineEdit_4.setGeometry(QtCore.QRect(150, 0, 50, 50))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_4.setMaxLength(1)
        self.lineEdit_4.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.widget_2)
        self.lineEdit_5.setGeometry(QtCore.QRect(0, 50, 50, 50))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_5.setFont(font)
        self.lineEdit_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_5.setMaxLength(1)
        self.lineEdit_5.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.widget_2)
        self.lineEdit_6.setGeometry(QtCore.QRect(50, 50, 50, 50))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_6.setFont(font)
        self.lineEdit_6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_6.setMaxLength(1)
        self.lineEdit_6.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.widget_2)
        self.lineEdit_7.setGeometry(QtCore.QRect(100, 50, 50, 50))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_7.setFont(font)
        self.lineEdit_7.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_7.setMaxLength(1)
        self.lineEdit_7.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.widget_2)
        self.lineEdit_8.setGeometry(QtCore.QRect(150, 50, 50, 50))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_8.setFont(font)
        self.lineEdit_8.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_8.setMaxLength(1)
        self.lineEdit_8.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.widget_2)
        self.lineEdit_9.setGeometry(QtCore.QRect(0, 100, 50, 50))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_9.setFont(font)
        self.lineEdit_9.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_9.setMaxLength(1)
        self.lineEdit_9.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.lineEdit_10 = QtWidgets.QLineEdit(self.widget_2)
        self.lineEdit_10.setGeometry(QtCore.QRect(50, 100, 50, 50))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_10.setFont(font)
        self.lineEdit_10.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_10.setMaxLength(1)
        self.lineEdit_10.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.lineEdit_11 = QtWidgets.QLineEdit(self.widget_2)
        self.lineEdit_11.setGeometry(QtCore.QRect(100, 100, 50, 50))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_11.setFont(font)
        self.lineEdit_11.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_11.setMaxLength(1)
        self.lineEdit_11.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.lineEdit_12 = QtWidgets.QLineEdit(self.widget_2)
        self.lineEdit_12.setGeometry(QtCore.QRect(150, 100, 50, 50))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_12.setFont(font)
        self.lineEdit_12.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_12.setMaxLength(1)
        self.lineEdit_12.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.lineEdit_13 = QtWidgets.QLineEdit(self.widget_2)
        self.lineEdit_13.setGeometry(QtCore.QRect(0, 150, 50, 50))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_13.setFont(font)
        self.lineEdit_13.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_13.setMaxLength(1)
        self.lineEdit_13.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.lineEdit_14 = QtWidgets.QLineEdit(self.widget_2)
        self.lineEdit_14.setGeometry(QtCore.QRect(50, 150, 50, 50))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_14.setFont(font)
        self.lineEdit_14.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_14.setMaxLength(1)
        self.lineEdit_14.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.lineEdit_15 = QtWidgets.QLineEdit(self.widget_2)
        self.lineEdit_15.setGeometry(QtCore.QRect(100, 150, 50, 50))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_15.setFont(font)
        self.lineEdit_15.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_15.setMaxLength(1)
        self.lineEdit_15.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.lineEdit_16 = QtWidgets.QLineEdit(self.widget_2)
        self.lineEdit_16.setGeometry(QtCore.QRect(150, 150, 50, 50))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_16.setFont(font)
        self.lineEdit_16.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_16.setMaxLength(1)
        self.lineEdit_16.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.resetbtn = QtWidgets.QPushButton(self.widget_2)
        self.resetbtn.setGeometry(QtCore.QRect(0, 240, 201, 28))
        self.resetbtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.resetbtn.setObjectName("resetbtn")
        self.lineEdit_8.raise_()
        self.lineEdit_7.raise_()
        self.lineEdit.raise_()
        self.lineEdit_2.raise_()
        self.lineEdit_3.raise_()
        self.lineEdit_4.raise_()
        self.lineEdit_5.raise_()
        self.lineEdit_6.raise_()
        self.lineEdit_9.raise_()
        self.lineEdit_10.raise_()
        self.lineEdit_11.raise_()
        self.lineEdit_12.raise_()
        self.lineEdit_13.raise_()
        self.lineEdit_14.raise_()
        self.lineEdit_15.raise_()
        self.lineEdit_16.raise_()
        self.resetbtn.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.resetbtn.clicked.connect(MainWindow.reset)
        self.lineEdit.textEdited['QString'].connect(MainWindow.textchange)
        self.lineEdit_2.textEdited['QString'].connect(MainWindow.textchange)
        self.lineEdit_3.textEdited['QString'].connect(MainWindow.textchange)
        self.lineEdit_4.textEdited['QString'].connect(MainWindow.textchange)
        self.lineEdit_5.textEdited['QString'].connect(MainWindow.textchange)
        self.lineEdit_6.textEdited['QString'].connect(MainWindow.textchange)
        self.lineEdit_7.textEdited['QString'].connect(MainWindow.textchange)
        self.lineEdit_8.textEdited['QString'].connect(MainWindow.textchange)
        self.lineEdit_9.textEdited['QString'].connect(MainWindow.textchange)
        self.lineEdit_10.textEdited['QString'].connect(MainWindow.textchange)
        self.lineEdit_11.textEdited['QString'].connect(MainWindow.textchange)
        self.lineEdit_12.textEdited['QString'].connect(MainWindow.textchange)
        self.lineEdit_13.textEdited['QString'].connect(MainWindow.textchange)
        self.lineEdit_14.textEdited['QString'].connect(MainWindow.textchange)
        self.lineEdit_15.textEdited['QString'].connect(MainWindow.textchange)
        self.lineEdit_16.textEdited['QString'].connect(MainWindow.textchange)
        self.bfsbtn.clicked.connect(MainWindow.runbfs)
        self.dfsbtn.clicked.connect(MainWindow.rundfs)
        self.idsbtn.clicked.connect(MainWindow.runids)
        self.Astarbtn.clicked.connect(MainWindow.runastar)
        self.depthlimit_input.textChanged['QString'].connect(MainWindow.depthLimitChange)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Blocksworld tile puzzle"))
        self.label_C.setText(_translate("MainWindow", "C"))
        self.label_B.setText(_translate("MainWindow", "B"))
        self.label_A.setText(_translate("MainWindow", "A"))
        self.Astarbtn.setText(_translate("MainWindow", "A*"))
        self.dfsbtn.setText(_translate("MainWindow", "DFS"))
        self.bfsbtn.setText(_translate("MainWindow", "BFS"))
        self.label_19.setText(_translate("MainWindow", "Depth Limit:"))
        self.depthlimit_input.setText(_translate("MainWindow", "15"))
        self.idsbtn.setText(_translate("MainWindow", "IDS"))
        self.label_action.setText(_translate("MainWindow", "Action sequences:"))
        self.label_13.setText(_translate("MainWindow", "Time Complexity:"))
        self.label_14.setText(_translate("MainWindow", "Depth:"))
        self.lineEdit_4.setText(_translate("MainWindow", "O"))
        self.lineEdit_13.setText(_translate("MainWindow", "A"))
        self.lineEdit_14.setText(_translate("MainWindow", "B"))
        self.lineEdit_15.setText(_translate("MainWindow", "C"))
        self.lineEdit_16.setText(_translate("MainWindow", "T"))
        self.resetbtn.setText(_translate("MainWindow", "Reset Start State"))
        self.statusbar.setStatusTip(_translate("MainWindow", "Author: Jiajie Chen, 2018-2020, University of Southampton"))

